export enum ChatActions {
  ADD_MESSAGE = "ADD_MESSAGE",
  ADD_MESSAGE_SUCCESS = "ADD_MESSAGE_SUCCESS",
  EDIT_MESSAGE = "EDIT_MESSAGE",
  DELETE_MESSAGE = "DELETE_MESSAGE",
  CHANGE_LIKE = "CHANGE_LIKE",
  INIT_STORAGE = "INIT_STORAGE",
  SET_STORAGE = "SET_STORAGE",
}
