export enum PageActions {
  HIDE_LOADING = "HIDE_LOADING",
  SHOW_LOADING = "SHOW_LOADING",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  SET_CURRENT_ID = "SET_CURRENT_ID",
  SET_USER_ROLE = "SET_USER_ROLE",
}
